steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: "feat-${CI_COMMIT_BRANCH##feat/}"
    secrets: [docker_username, docker_password]
when:
  branch:
    - feat/*
  event: push
